using System.Text.Json;
using System.Text.Json.Serialization;

using YTLiveChat.Models;
using YTLiveChat.Models.Response;

namespace YTLiveChat.Helpers;

[JsonSerializable(typeof(LiveChatRequest))]
[JsonSerializable(typeof(RequestContext))]
[JsonSerializable(typeof(ClientInfo))]
[JsonSerializable(typeof(LiveChatResponse))]
[JsonSerializable(typeof(ContinuationContents))]
[JsonSerializable(typeof(LiveChatContinuation))]
[JsonSerializable(typeof(Models.Response.Action))]
[JsonSerializable(typeof(AddChatItemAction))]
[JsonSerializable(typeof(AddChatItemActionItem))]
[JsonSerializable(typeof(RemoveChatItemAction))]
[JsonSerializable(typeof(ReplaceChatItemAction))]
[JsonSerializable(typeof(ReplacementItem))]
[JsonSerializable(typeof(RemoveChatItemByAuthorAction))]
[JsonSerializable(typeof(AddLiveChatTickerItemAction))]
[JsonSerializable(typeof(AddLiveChatTickerItemActionItem))]
[JsonSerializable(typeof(LiveChatTextMessageRenderer))]
[JsonSerializable(typeof(LiveChatPaidMessageRenderer))]
[JsonSerializable(typeof(LiveChatPaidStickerRenderer))]
[JsonSerializable(typeof(LiveChatMembershipItemRenderer))]
[JsonSerializable(typeof(LiveChatSponsorshipsGiftPurchaseAnnouncementRenderer))]
[JsonSerializable(typeof(LiveChatSponsorshipsGiftRedemptionAnnouncementRenderer))]
[JsonSerializable(typeof(LiveChatPlaceholderItemRenderer))]
[JsonSerializable(typeof(Message))]
[JsonSerializable(typeof(MessageRun))]
[JsonSerializable(typeof(MessageText))]
[JsonSerializable(typeof(MessageEmoji))]
[JsonSerializable(typeof(HeaderText))]
[JsonSerializable(typeof(SimpleText))]
[JsonSerializable(typeof(Emoji))]
[JsonSerializable(typeof(EmojiImage))]
[JsonSerializable(typeof(Thumbnail))]
[JsonSerializable(typeof(AuthorPhoto))]
[JsonSerializable(typeof(Accessibility))]
[JsonSerializable(typeof(AccessibilityData))]
[JsonSerializable(typeof(Icon))]
[JsonSerializable(typeof(AuthorBadgeContainer))]
[JsonSerializable(typeof(LiveChatAuthorBadgeRenderer))]
[JsonSerializable(typeof(CustomThumbnail))]
[JsonSerializable(typeof(PurchaseAmountText))]
[JsonSerializable(typeof(Sticker))]
[JsonSerializable(typeof(SponsorshipsHeaderContainer))]
[JsonSerializable(typeof(LiveChatSponsorshipsHeaderRenderer))]
[JsonSerializable(typeof(Source))]
[JsonSerializable(typeof(IconSource))]
[JsonSerializable(typeof(Continuation))]
[JsonSerializable(typeof(InvalidationContinuationData))]
[JsonSerializable(typeof(TimedContinuationData))]
[JsonSerializable(typeof(ResponseContext))]
[JsonSerializable(typeof(MainAppWebResponseContext))]
[JsonSerializable(typeof(ServiceTrackingParam))]
[JsonSerializable(typeof(Param))]
[JsonSerializable(typeof(WebResponseContextExtensionData))]
[JsonSerializable(typeof(FrameworkUpdates))]
[JsonSerializable(typeof(EntityBatchUpdate))]
[JsonSerializable(typeof(Mutation))]
[JsonSerializable(typeof(MutationPayload))]
[JsonSerializable(typeof(Timestamp))]
[JsonSerializable(typeof(LiveChatStreamingResponseExtension))]
[JsonSerializable(typeof(ReactionControlPanelOverlayViewModel))]
[JsonSerializable(typeof(SignalAction))]
[JsonSerializable(typeof(LiveChatParticipantRenderer))]
[JsonSerializable(typeof(NavigationEndpoint))]
[JsonSerializable(typeof(CommandMetadata))]
[JsonSerializable(typeof(WebCommandMetadata))]
[JsonSerializable(typeof(UrlEndpoint))]
[JsonSerializable(typeof(ContextMenuEndpoint))]
[JsonSerializable(typeof(LiveChatItemContextMenuEndpoint))]
[JsonSerializable(typeof(LiveChatTickerShowItemRenderer))]
[JsonSerializable(typeof(ShowLiveChatItemEndpoint))]
[JsonSerializable(typeof(TickerShowItemEndpoint))]
[JsonSerializable(typeof(LiveChatTickerPaidMessageItemRenderer))]
[JsonSerializable(typeof(LiveChatTickerSponsorItemRenderer))]
[JsonSerializable(typeof(LiveChatTickerPaidStickerItemRenderer))]
[JsonSerializable(typeof(ButtonViewModel))]
[JsonSerializable(typeof(BeforeContentButtonContainer))]
[JsonSerializable(typeof(MessageRendererBase))]
internal partial class YTLiveChatJsonSerializerContext : JsonSerializerContext
{
}
